on: push

jobs:
  build:
    name: Build & Publish Cart
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build C colorbars cart
        run: docker run -v ./carts/c/colorbars:/src -v .:/out konsumer/null0-cart-c colorbars_c
      - name: Upload C colorbars cart artifact
        uses: actions/upload-artifact@v4
        with:
          name: colorbars_c
          path: colorbars_c.null0
